## 2. Creating Arrays

In [2]:
import numpy as np
# 1D Array
arr = np.array([1, 2, 3, 4])
print('1D Array:', arr)

# 2D Array
arr_2d = np.array([[1, 2], [3, 4]])
print('2D Array:')
print( arr_2d)

print('Shape of 1D array:', arr.shape)
print('Shape of 2D array:', arr_2d.shape)
print('Data type of elements:', arr.dtype)

1D Array: [1 2 3 4]
2D Array:
[[1 2]
 [3 4]]
Shape of 1D array: (4,)
Shape of 2D array: (2, 2)
Data type of elements: int64


## 4. Basic Operations

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
add = arr1 + arr2
print('Addition:', add)

# Element-wise multiplication
mul = arr1 * arr2
print('Multiplication:', mul)

# Indexing
print('First element of arr1:', arr1[0])

# Slicing
print('Elements from index 1 to 2:', arr1[1:3])

# 2D Array indexing
print('Element at row 0, col 1 in arr_2d:', arr_2d[0, 1])
print('Element at row 0, col 1 in arr_2d:', arr_2d[0][1])

Addition: [5 7 9]
Multiplication: [ 4 10 18]
First element of arr1: 1
Elements from index 1 to 2: [2 3]
Element at row 0, col 1 in arr_2d: 2
Element at row 0, col 1 in arr_2d: 2


## 3. Array Initialization And Reshaping

In [4]:
zeros = np.zeros((2, 2))
ones = np.ones((3, 3))
random = np.random.rand(2, 3)
print('Zeros:', zeros)
zeros[:][:]=1
print('Zeros:', zeros)
print('Ones:', ones)
print('Random values:', random)

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print('Reshaped array:', arr.reshape((2, 3)))

print('Transposed array:', arr.reshape((2, 3)).T)



Zeros: [[0. 0.]
 [0. 0.]]
Zeros: [[1. 1.]
 [1. 1.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random values: [[0.23020738 0.71509772 0.08327382]
 [0.50630315 0.78865027 0.3356557 ]]
Reshaped array: [[1 2 3]
 [4 5 6]]
Transposed array: [[1 4]
 [2 5]
 [3 6]]


## 8. Mathematical Functions

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Max:', np.sin(arr))
print('Sin:', np.exp(arr))
print('log base x:', np.log10(arr))

Sum: 15
Mean: 3.0
Max: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Sin: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log base x: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


## 9. Linear Algebra Operations

In [6]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)
print('Matrix multiplication:', result)

# Determinant
det = np.linalg.det(matrix1)
print('Determinant of matrix1:', det)

# Mean / Deviation / Variance
print("mean of array",np.mean(matrix1))#all elemnents, shape doesnt matter
# print("mean of array",np.median(matrix1))#all elemnents, shape doesnt matter
# print("mean of array",np.std(matrix1))#all elemnents, shape doesnt matter
# print("mean of array",np.var(matrix1))#all elemnents, shape doesnt matter


Matrix multiplication: [[19 22]
 [43 50]]
Determinant of matrix1: -2.0000000000000004
mean of array 2.5


## Logical Operations

In [7]:
data= np.array([[8,3,6],[5,7,4]])
print(data>5)
print()
print(data[data>5])


[[ True False  True]
 [False  True False]]

[8 6 7]
